// Code generated by go-swagger; DO NOT EDIT.

package trip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddNewTripHandlerFunc turns a function with the right signature into a add new trip handler
type AddNewTripHandlerFunc func(AddNewTripParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddNewTripHandlerFunc) Handle(params AddNewTripParams) middleware.Responder {
	return fn(params)
}

// AddNewTripHandler interface for that can handle valid add new trip params
type AddNewTripHandler interface {
	Handle(AddNewTripParams) middleware.Responder
}

// NewAddNewTrip creates a new http.Handler for the add new trip operation
func NewAddNewTrip(ctx *middleware.Context, handler AddNewTripHandler) *AddNewTrip {
	return &AddNewTrip{Context: ctx, Handler: handler}
}

/* AddNewTrip swagger:route POST /trip trip addNewTrip

Add a new trip to the packandgo

*/
type AddNewTrip struct {
	Context *middleware.Context
	Handler AddNewTripHandler
}

func (o *AddNewTrip) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddNewTripParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
