// Code generated by go-swagger; DO NOT EDIT.

package trip

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bus-company/models"
)

// AddNewTripCreatedCode is the HTTP code returned for type AddNewTripCreated
const AddNewTripCreatedCode int = 201

/*AddNewTripCreated Successfully created the trip

swagger:response addNewTripCreated
*/
type AddNewTripCreated struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddNewTripCreated creates AddNewTripCreated with default headers values
func NewAddNewTripCreated() *AddNewTripCreated {

	return &AddNewTripCreated{}
}

// WithPayload adds the payload to the add new trip created response
func (o *AddNewTripCreated) WithPayload(payload *models.APIResponse) *AddNewTripCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add new trip created response
func (o *AddNewTripCreated) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddNewTripCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddNewTripMethodNotAllowedCode is the HTTP code returned for type AddNewTripMethodNotAllowed
const AddNewTripMethodNotAllowedCode int = 405

/*AddNewTripMethodNotAllowed Invalid input

swagger:response addNewTripMethodNotAllowed
*/
type AddNewTripMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddNewTripMethodNotAllowed creates AddNewTripMethodNotAllowed with default headers values
func NewAddNewTripMethodNotAllowed() *AddNewTripMethodNotAllowed {

	return &AddNewTripMethodNotAllowed{}
}

// WithPayload adds the payload to the add new trip method not allowed response
func (o *AddNewTripMethodNotAllowed) WithPayload(payload *models.APIResponse) *AddNewTripMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add new trip method not allowed response
func (o *AddNewTripMethodNotAllowed) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddNewTripMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
