// Code generated by go-swagger; DO NOT EDIT.

// Package restapi PackAndGo Application
//
//  This is a pack-and-go bus company Swagger API to manage the trips that PackAndGo offers
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//  Host: packandgo.com
//  BasePath: /v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <apiteam@packandgo.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
