// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddTrip add trip
//
// swagger:model AddTrip
type AddTrip struct {

	// dates
	// Required: true
	Dates *string `json:"dates"`

	// destination Id
	// Required: true
	DestinationID *float64 `json:"destinationId"`

	// origin Id
	// Required: true
	OriginID *float64 `json:"originId"`

	// price
	// Required: true
	Price *float32 `json:"price"`
}

// Validate validates this add trip
func (m *AddTrip) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDestinationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOriginID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrice(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddTrip) validateDates(formats strfmt.Registry) error {

	if err := validate.Required("dates", "body", m.Dates); err != nil {
		return err
	}

	return nil
}

func (m *AddTrip) validateDestinationID(formats strfmt.Registry) error {

	if err := validate.Required("destinationId", "body", m.DestinationID); err != nil {
		return err
	}

	return nil
}

func (m *AddTrip) validateOriginID(formats strfmt.Registry) error {

	if err := validate.Required("originId", "body", m.OriginID); err != nil {
		return err
	}

	return nil
}

func (m *AddTrip) validatePrice(formats strfmt.Registry) error {

	if err := validate.Required("price", "body", m.Price); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this add trip based on context it is used
func (m *AddTrip) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddTrip) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddTrip) UnmarshalBinary(b []byte) error {
	var res AddTrip
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
